# Generated by Django 4.2.2 on 2023-06-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_review_recommended_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='City',
            field=models.TextField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='Governorate',
            field=models.TextField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='Sector',
            field=models.TextField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='Subject',
            field=models.TextField(default='NA', max_length=50),
        ),
    ]
